# Generated by Django 4.2.6 on 2023-11-01 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'managed': True, 'verbose_name': 'Products', 'verbose_name_plural': 'Products'},
        ),
    ]
