# Generated by Django 4.2.6 on 2023-11-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='refers_to',
        ),
    ]
