# Generated by Django 4.2.6 on 2023-11-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_reviews_refers_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'managed': True, 'ordering': ('-post_date',), 'verbose_name': 'Products', 'verbose_name_plural': 'Products'},
        ),
    ]
