# Generated by Django 4.2.6 on 2023-11-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_products_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufactureyear',
            name='name',
            field=models.PositiveIntegerField(),
        ),
    ]
